import * as esbuild from 'esbuild'
import {readFileSync, writeFileSync} from 'fs'

// Build the worker as a standalone bundle
await esbuild.build({
  entryPoints: ['src/argon-worker.js'],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  outfile: 'dist/argon-worker.bundle.js',
  minify: true,
})

// Read the bundled worker code
const workerCode = readFileSync('dist/argon-worker.bundle.js', 'utf-8')

// Generate a TypeScript file with the worker code as a string
const tsContent = `// This file is auto-generated by build-worker.js
/* eslint prettier/prettier: 0 */
export const ARGON_WORKER_CODE = ${JSON.stringify(workerCode)};
`

writeFileSync('src/argon-worker-code.ts', tsContent)
